version: "3.5"
services:
  mysql: 
    image: benlumia007/mysql:5.7
    container_name: mysql
    environment: 
        MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    restart: always