# docker-setup.yml
#
# This is the main YAML formatted file which is done in spaces and not tabs, and whitespace.
# If you do not stick to the format. it will fail on provision.

# Important Note
#
# If you need to add a new site, copy the example and uncomment the lines and enter the site name.
# You wil then need to run when you use make.
sites:
  classicpress:
    provision: true
    repo: https://github.com/benlumia007/sturdy-docker-sites.git
    host:
      - classicpress.test
    custom:
      type: ClassicPress
      plugins:
        - query-monitor
      constants:
        - DISALLOW_FILE_EDIT
        - WP_DEBUG
        - WP_DEBUG_DISPLAY

  sandbox:
    provision: true
    repo: https://github.com/benlumia007/sturdy-docker-sites.git
    host:
      - sandbox.test
    custom:
      type: WordPress
      plugins:
        - query-monitor
      constants:
        - DISALLOW_FILE_EDIT
        - WP_DEBUG
        - WP_DEBUG_DISPLAY

  wordpress:
    provision: true
    repo: https://github.com/benlumia007/sturdy-docker-sites.git
    host:
      - wordpress.test
    custom:
      type: WordPress
      plugins:
        - gutenberg
        - query-monitor
      constants:
        - DISALLOW_FILE_EDIT
        - WP_DEBUG
        - WP_DEBUG_DISPLAY


resources:
  - phpmyadmin
  - tls-ca

options:
  db_backups: true
  db_restores: true
